#config for blog

database:
    name: "blog"
    dbtype: "mysql"
    user: "root"
    password: ""
    ip: "127.0.0.1"
    port: "3306"
    charset: "utf8mb4"
    parsetime: "True"

# score to active user
score:
    post: 8
    comment: 1

elastic:
    host: localhost
    port: 9200
